name: nimbus
description: "a cloud storage that respects your privacy"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconify_flutter: ^0.0.7
  photo_manager: ^3.7.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  path: ^1.9.1
  better_player_plus: ^1.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/samples/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
