// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYP9P1TFC5arbuo45oRrAZkb9WQYsLMQ',
    appId: '1:304860441462:web:58c3cffc9d1903340ce857',
    messagingSenderId: '304860441462',
    projectId: 'nimbus-3d8b0',
    authDomain: 'nimbus-3d8b0.firebaseapp.com',
    storageBucket: 'nimbus-3d8b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvO6-OWhC61D7pgTr0Z3Snrm2xkBPi4s',
    appId: '1:304860441462:android:aff8794222d9d3a50ce857',
    messagingSenderId: '304860441462',
    projectId: 'nimbus-3d8b0',
    storageBucket: 'nimbus-3d8b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPfQ-8lqrLD4mYokoyigpX75hgISXiByg',
    appId: '1:304860441462:ios:b8cb9829dc3d573a0ce857',
    messagingSenderId: '304860441462',
    projectId: 'nimbus-3d8b0',
    storageBucket: 'nimbus-3d8b0.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfQ-8lqrLD4mYokoyigpX75hgISXiByg',
    appId: '1:304860441462:ios:b8cb9829dc3d573a0ce857',
    messagingSenderId: '304860441462',
    projectId: 'nimbus-3d8b0',
    storageBucket: 'nimbus-3d8b0.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCYP9P1TFC5arbuo45oRrAZkb9WQYsLMQ',
    appId: '1:304860441462:web:ea90290f8b7896400ce857',
    messagingSenderId: '304860441462',
    projectId: 'nimbus-3d8b0',
    authDomain: 'nimbus-3d8b0.firebaseapp.com',
    storageBucket: 'nimbus-3d8b0.firebasestorage.app',
  );
}
